-- MongoDB Schema for UnityCare Platform
-- Note: Actual schema is defined in backend/src/models/ via Mongoose.
-- This file serves as reference documentation for the MongoDB collections.

-- Users Collection (via Mongoose model: backend/src/models/User.js)
-- {
--   _id: ObjectId,
--   name: String (required),
--   email: String (required, unique, lowercase),
--   password: String (required, bcrypt hashed),
--   role: String (enum: patient|doctor|admin|pharmacist|nurse, default: patient),
--   invalidatedTokens: [String],
--   createdAt: Date,
--   updatedAt: Date
-- }

-- Appointments Collection (via Mongoose model: backend/src/models/Appointment.js)
-- {
--   _id: ObjectId,
--   date: Date (required),
--   time: String (required),
--   patient: ObjectId (ref: User, required),
--   doctor: ObjectId (ref: User, required),
--   notes: String,
--   status: String (enum: pending|confirmed|completed|cancelled, default: pending),
--   createdAt: Date,
--   updatedAt: Date
-- }
-- Indexes: { doctor: 1, date: 1, time: 1, status: 1 }
-- Indexes: { patient: 1, date: -1 }

-- MedicalRecords Collection (via Mongoose model: backend/src/models/MedicalRecord.js)
-- {
--   _id: ObjectId,
--   patient: ObjectId (ref: User, required),
--   doctor: ObjectId (ref: User, required),
--   diagnosis: String (required),
--   treatment: String (required),
--   medications: [{ name, dosage, frequency, duration }],
--   notes: String,
--   attachments: [{ filename, url, uploadedAt }],
--   integrityHash: String,
--   deletedAt: Date (nullable, for GDPR soft-delete),
--   createdAt: Date,
--   updatedAt: Date
-- }
-- Indexes: { patient: 1, createdAt: -1 }

